name: Upload dotnet package

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # SDK Version to use.
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
    - run: dotnet build --configuration Release OneBlink.SDK
    - name: Create the package
    run: dotnet pack --configuration Release OneBlink.SDK
    - name: Publish the package to Nuget
    run: dotnet nuget push OneBlink.SDK/bin/Release/*.nupkg --api-key $NUGET_API_KEY